// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCfxcvmsL4EmhOMo45jdix0-DApcd1r0Q',
    appId: '1:644842219915:web:ec7fa2c4af4ed646e9278e',
    messagingSenderId: '644842219915',
    projectId: 'pmsn2025-54f3e',
    authDomain: 'pmsn2025-54f3e.firebaseapp.com',
    storageBucket: 'pmsn2025-54f3e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZxluIw2FcP1VgkZdGPvm34vnVR5nHa3I',
    appId: '1:644842219915:android:867d11997fd40b69e9278e',
    messagingSenderId: '644842219915',
    projectId: 'pmsn2025-54f3e',
    storageBucket: 'pmsn2025-54f3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5NPEKb5uGuI9vxI3bW7h4CTu4uq6vzdo',
    appId: '1:644842219915:ios:c2e91a19f4481933e9278e',
    messagingSenderId: '644842219915',
    projectId: 'pmsn2025-54f3e',
    storageBucket: 'pmsn2025-54f3e.firebasestorage.app',
    iosBundleId: 'com.example.pmsn20252',
  );
}
